//@author ypijs.org#license 2014
function g(b){var a={D:[],la:[]};a.name=b.Name;a.Ra=b.Alias;a.sb=b.TextAbout;a.speed=b.Speed;a.va=b.IdleInterval;a.message=void 0;a.ja=1;a.Fb=void 0;a.F="#"+b.BubbleId;a.ia=b.onbubble;a.Da=b.onplay;a.Ha=b.onstop;a.Ca=b.onmute;a.Nb=b.onaction;a.Fa=b.onseek;a.Ga=b.onsetter;a.T=b.onfinish;a.aa=b.behavior;a.J=!1;a.i=0;a.A=0;a.pb=function(b){a.la=b.split("\\n");a.A=0;a.i=0};a.ob=function(b){a.Ia=b};a.getParams=function(){return a.Ia};a.getName=function(){return a.name};a.getAlias=function(){return a.Ra};
a.ua=function(){return a.i<a.la.length};a.jb=function(){if(a.ua())return a.i+=1,a.la[a.i-1]};a.registerCustomAction=function(b,f){a.D[b]=f};a.update=function(b,f){a.ub();return void 0==a.D[b]||void 0==a.D[b].Na||a.D[b].Qa!=f.Qa?!1:a.D[b].Na(void 0,f)};a.ub=function(){a.ja=1;void 0!=a.Q&&clearTimeout(a.Q)};a.w=function(b,f){void 0!=f&&(a.first=f.na);a.A=0;a.message=b;void 0!=a.Q&&clearTimeout(a.Q);a.J&&(clearTimeout(a.timeout),a.J=!1);a.pb(b);a.La()};a.La=function(){retVal=!0;void 0!=a.Da&&k.I&&(retVal=
!a.Da(a));retVal&&a.show()};a.show=function(){a.ya?a.ra=!0:a.Ua(a.jb())};a.skip=function(){clearTimeout(a.timeout);a.mute()};a.repeat=function(){a.w(a.message);a.ja++};a.about=function(b){temp=a.message;a.w(b);a.message=temp};a.getTextAbout=function(){return a.sb};a.getTextId=function(){return a.A};a.Ua=function(b){void 0!=a.ia?(px={},px.Text=b,px.Element=$(a.F),a.ia(px,a)):$(a.F).text(b);retVal=a.J=!0;void 0!=a.Fa&&k.I&&(retVal=!a.Fa(a));retVal&&(a.timeout=setTimeout(function(){a.J&&a.mute()},b.length*
a.speed));$(a.F).fadeIn(30,function(){a.first&&(k.qb(a.Ia),a.first=!1);k.update(a)})};a.isSpeaking=function(){return a.J};a.mute=function(){void 0!=a.Ca&&a.Ca(a);a.ya=!0;$(a.F).fadeOut("slow",a.ib)};a.ib=function(){a.ya=!1;a.ra?(a.ra=!1,a.show()):a.ua()?(a.A+=1,a.La()):k.za()||a.tb()};a.tb=function(){void 0!=a.Ha&&a.Ha(a);a.A=0;void 0!=a.va&&(a.Q=setTimeout(function(){a.repeat()},a.va*a.ja))};return a}
function l(){return hR={update:function(b){$("#history").empty();$.each(b.ha,function(){historyItem=this;$("<strong>"+historyItem.ma+"</strong><p>"+historyItem.b+"</p>").appendTo("#history")});$hide=$("<a>hide</a>");$hide.click(function(){b.hide();$("#history_panel").fadeOut("fast");$("#history").empty()}).appendTo("#history")},lb:function(b){$("#history_panel").fadeIn("fast");hR.update(b)}}}
function m(){mH={ha:{},Ma:{},Qb:{},Ja:void 0,ga:!1};mH.j=l();mH.i=0;mH.Ka=function(b){mH.Ma[b.r]=!0;mH.ha[mH.i]=b;mH.i++;mH.update()};mH.nb=function(b){mH.Ja=b};mH.Gb=function(){return mH.Ja};mH.gb=function(b){return!0==mH.Ma[b]};mH.show=function(){mH.ga=!0;mH.j.lb(mH)};mH.update=function(){mH.ga&&mH.j.update(mH)};mH.hide=function(){mH.ga=!1};return mH}
function n(){aU={h:[],m:[]};var b=m();aU.register=function(a,b){aU.h[a]=b;void 0!=b.aa&&b.aa(b)};aU.reset=function(){aU.m=[]};aU.ka=function(a){if(isNaN(a.C))return!1;void 0==aU.m[a.f]&&(aU.m[a.f]=0);if("+="==a.Y)aU.m[a.f]+=Number(a.C);else if("="==a.Y)aU.m[a.f]=Number(a.C);else return!1;void 0!=aU.K&&aU.K(a);return!0};aU.P=function(a){return aU.m[a]};aU.eb=function(){for(var a in aU.h)void 0!=aU.h[a].Ga&&aU.h[a].Ga()};aU.sa=function(a){return aU.h[a]};aU.u=function(){return b};aU.w=function(a,d){void 0!=
d.q&&void 0!=aU.h[d.q]&&($v=$(aU.h[d.q].F),void 0!=$v&&"hide"!=d.Oa&&(b.Ka({ma:d.q,b:a}),aU.h[d.q].w(a,d)))};return aU}
function q(b,a){pR={};pR.d=a;pR.fa=void 0;pR.H=b.initState;pR.R=b.isAutostart;pR.xml=void 0;pR.load=function(a){pR.fa=!1;$.ajax({type:"GET",url:a,dataType:"xml",success:function(a){pR.xml=$(a);pR.fa=!0;void 0!=pR.R&&void 0!=pR.H&&pR.R&&pR.d.M(pR.H)},error:function(){void 0!=pR.d.Aa&&pR.d.Aa(a)}})};pR.$a=function(a){var b={};$.each(pR.d.Sa,function(e,c){b[c.charAt(0).toUpperCase()+c.substring(1)]=a.getAttribute(c)});b.b=b.Text;b.g=b.Target;b.X=b.Invoke;b.yb=b.Overtime;b.Bb=b.Timeout;b.Z=b.Sound;b.B=
b.Id;void 0!=pR.d.oa&&$.each(pR.d.oa,function(e,c){b[c.charAt(0).toUpperCase()+c.substring(1)]=a.getAttribute(c)});return void 0==b.b?void 0:b};pR.ta=function(){var a=element,b={};b.o=a.getAttribute("prop");$.each(pR.d.Ta,function(e,c){b[c.charAt(0).toUpperCase()+c.substring(1)]=a.getAttribute(c)});b.n=b.Goto;b.b=b.Text;b.N=b.Condition;b.zb=b.Prop;b.p=b.Setter;b.Z=b.Sound;b.X=b.Invoke;void 0!=pR.d.pa&&$.each(pR.d.pa,function(e,c){b[c.charAt(0).toUpperCase()+c.substring(1)]=a.getAttribute(c)});return void 0==
b.b&&void 0==GotoId?void 0:b};pR.hb=function(a,b,e){diff=100-b;0<diff&&(p=Math.floor(diff/e),$.each(a,function(){void 0==this.o&&(this.o=p)}))};pR.kb=function(b){tokens=b.split(";");for(i=0;i<tokens.length;i++)0==tokens[i].indexOf("_")&&0<tokens[i].indexOf("=")&&(variables=tokens[i].split("="),isNaN(variables[1])?alert(tokens[i]+": invalid number format"):variables[0].indexOf("+")==variables[0].length-1?a.e.ka({f:variables[0].substring(0,variables[0].length-1),Y:"+=",C:variables[1]}):a.e.ka({f:variables[0],
Y:"=",C:variables[1]}));a.e.eb()};pR.Za=function(a){var b=Math.floor(100*Math.random()+1),e=void 0,c=0;$.each(a,function(){if(pR.fb(this,b,c))return e=this,!1;c+=Number(this.o);return!0});return e};pR.fb=function(a,b,e){return b>e&&b<=e+Number(a.o)};pR.da=function(){return pR.xml};pR.ab=function(a,b){if(void 0==b)return a;x=a.lastIndexOf(".");if(0>=x)return a;prefix=a.substring(0,x);suffix=a.substring(x,a.length);return prefix+"_"+b+suffix};return pR}
function t(b){iN={data:"",index:0,lastIndex:0,ha:"",O:0,K:void 0};void 0!=b&&void 0!=b.onvariable&&(iN.K=b.onvariable);iN.log=function(){};iN.evaluate=function(a){iN.data=decodeURI(a.replace(/\^/g,"&"));iN.index=0;iN.O=0;return r=iN.t()};iN.t=function(){expected=iN.next();if("("==expected){iN.O++;tmp=iN.t();expected=iN.next();if(")"==expected)return iN.O--,expected=iN.next(),"|"==expected?tmp|=iN.t():")"==expected?iN.L():"&"==expected?tmp&=iN.t():iN.v()||iN.c(expected,"& or |"),tmp;iN.c(expected,
")")}else{if("_"==expected)return tmp=iN.Xa(),expected=iN.next(),"|"==expected?tmp|=iN.t():"&"==expected?tmp&=iN.t():")"==expected?(0>=iN.O&&iN.c(expected,"unexpected )"),iN.L()):iN.v()||iN.c(expected,"& or |"),tmp;iN.c(expected,"_ or (")}};iN.Xa=function(){variable=iN.P();val=0;void 0!=iN.K&&(val=iN.K("_"+variable),void 0==val&&(val=0));expected=iN.next();"="==expected?tmp=val==iN.ca():">"==expected?tmp=val>iN.ca():"<"==expected?tmp=val<iN.ca():iN.c("bad operator","expected ><=");return tmp};iN.Ib=
function(a){return"x"==a?1:0};iN.P=function(){for(str="";;){expected=iN.next();if("="==expected||">"==expected||"<"==expected)return iN.L(),""==str?iN.c("empty name of property"):iN.log("got variable "+str),str;if("\n"==expected||iN.v()){iN.c(expected);break}else str+=expected}};iN.ca=function(){str="";expected=iN.next();for("-"==expected?str+=expected:iN.L();;)if(expected=iN.next(),"1"==expected||"2"==expected||"3"==expected||"4"==expected||"5"==expected||"6"==expected||"7"==expected||"8"==expected||
"9"==expected||"0"==expected)str+=expected;else{if("&"==expected||"|"==expected||"\n"==expected||")"==expected||","==expected||"+"==expected||iN.v())return iN.L(),""==str&&iN.c("empty constant"),str;iN.c(expected,"");break}};iN.c=function(a,b){throw'error: "'+a+'",'+b;};iN.v=function(){return iN.index+1>iN.data.length};iN.L=function(){iN.index=iN.lastIndex};iN.rb=function(){for(;!(iN.index++,iN.v()||"\r"!=iN.data.charAt(iN.index-1)&&" "!=iN.data.charAt(iN.index-1)););};iN.next=function(){return iN.v()?
null:(iN.lastIndex=iN.index,iN.rb(),iN.data.charAt(iN.index-1))};return iN}
function u(){return rd={Wa:function(b,a){a.S&&void 0!=b.N&&1!=a.evaluate(b.N)||(cssClass="",a.u().gb(b.r)&&(cssClass="class=visited"),void 0!=b&&(s=void 0,void 0!=a.Ea&&(s=a.Ea(b)),void 0==s&&(s=$("<li "+cssClass+"></li>").html('<a href="#'+b.g+'_area">'+b.b+"</a>")),s.click({b:b.b,n:b.n,r:b.r,W:b.W,p:b.p,Pa:b},function(b){a.u().nb(b.data.W);a.u().Ka({ma:"you",b:b.data.b,r:b.data.r});void 0!=b.data.p&&a.a.kb(b.data.p);a.M(b.data.n);void 0!=a.Ba&&a.Ba(b.data.Pa)}),s.appendTo("#answers")))},mb:function(b){return b},
wa:function(){$('<ul id="answers"></ul>').appendTo("#dialog")}}}
var k=function(){var b={init:function(a){b.a=void 0;b.j=void 0;b.e=n();b.s=void 0;b.G=a.chapterUrl;b.xa=a.onload;b.Ba=a.onanswer;b.Ea=a.onrender;b.Aa=a.on404;b.U=a.onsound;b.T=a.onfinish;b.oa=a.attrCase;b.pa=a.attrReact;b.Sa="id text target sound overtime timeout invoke".split(" ");b.Ta="text goto condition invoke sound setter".split(" ");b.language=a.language;b.a=q(a,b);b.j=u();b.I=!1;b.I=a.isSoundEnabled;b.S=!0;b.ea=void 0;!1==a.isExprEnabled&&(b.S=!1);b.qa=a.disableBubbleRender;b.$=1;b.V=0},invokeInit:function(){if(void 0==
b.xa||void 0==b.a)return!1;b.j.wa();b.xa();b.bb();void 0!=b.G&&(b.S&&(b.ea=t({onvariable:b.e.P})),b.a.load(b.a.ab(b.G,b.language)))},reset:function(){b.e.reset();b.M(b.a.H);temp=avatar.message},l:function(){return b.e},Hb:function(){return b.j()},createAvatar:function(a){void 0==a.BubbleId&&(a.BubbleId="npc_bubble_"+b.$);void 0==a.Name&&(a.Name="avatar_"+b.$);a=g(a);if(void 0!=a&&void 0!=b.l())return b.l().register(a.name,a),b.$++,a},u:function(){return b.l().u()},gotoChapter:function(a){void 0!=
a.nodeId&&(b.e.reset(),void 0!=a.chapterUrl&&a.chapterUrl!=b.G?(b.a.H=a.nodeId,b.G=a.chapterUrl,b.a.R=!0,b.a.load(b.G)):b.M(a.nodeId))},M:function(a){if(void 0==b.a||!0!=b.a.fa)return!1;$("#answers").empty();var d;b.a.da().find("case[id="+a+"]").each(function(){d=this});a=b.a.$a(d);if(void 0==a)return!1;b.Ya(a);b.V=0;b.ba=a;void 0!=a.k?b.za():b.show(a)},za:function(){if(void 0==b.ba.k||b.V>=b.ba.k.length)return!1;params=b.ba.k[b.V];b.V++;b.show(params);return!0},Ya:function(a){tCnt=0;b.a.da().find("txt[rel="+
a.B+"]").each(function(){element=this;params=b.a.ta();void 0!=params.b&&b.S&&void 0!=params.N&&1!=b.evaluate(params.N)||(void 0==a.k&&(a.k=[],void 0!=a.b&&0<a.b.length?(a.k[tCnt]=a,tCnt++):(params.g=a.g,params.B=a.B)),a.k[tCnt]=params,tCnt++)})},show:function(a){b.cb(a)},qb:function(a){var d=0,f=0,e=0,c=[];nodeId=a.B;b.a.da().find("react[rel="+nodeId+"]").each(function(){element=this;params=b.a.ta();params.r=nodeId+""+params.n;params.W=nodeId;params.g=a.g;void 0!=params.o?e+=Number(params.o):f+=1;
c[d]=params;d++;0==e&&b.j.Wa(params,b)});$("#answer_widget").fadeIn("slow");if(0<e){b.a.hb(c,e,f);var h=b.a.Za(c);void 0!=h&&void 0!=h.n&&setTimeout(function(){void 0!=h.p&&b.a.Ob(h.p);b.M(h.n)},5E3)}0==d&&void 0!=b.T&&b.T(a)},update:function(){},invokeActions:function(a){avatar=k.l().sa(b.s);void 0!=avatar&&void 0!=a.X&&avatar.update(a.X,a)},cb:function(a){a.g!=b.s&&void 0!=a.g&&(b.l().w("",{q:b.s,Oa:"hide",na:!0}),b.s=a.g);if(void 0==b.qa||!1==b.qa)a.b=b.j.mb(a.b);avatar=k.l().sa(b.s);avatar.ob(a);
    b.l().w(a.b, { q: b.s, na: !0 })
}, Jb: function () { b.u().show() }, bb: function () { if (!b.I || void 0 == b.U) return !1; px = { Type: "INIT" }; b.U(px) }, Pb: function (a) { if (!b.I || void 0 == b.U || void 0 == a.Z) return !1; px = { Type: "PLAY" }; px.Id = a.B; px.Sound = a.Z; px.Param = a; b.U(px) }, getVariable: function (a) { return b.e.P(a) }, setVariable: function (a, d) { b.e.ka({ f: a, C: d }) }, evaluate: function (a) { if (void 0 == b.ea || void 0 == a || 3 >= a.length) return null; try { return r = b.ea.evaluate(a) } catch (d) { return null } } 
}; return b} (""), ypi = {}; ypi.df = k;

