//@author ypijs.org#license 2014
function g(b){var a={A:[],fa:[]};a.name=b.Name;a.ka=b.Alias;a.speed=b.Speed;a.ra=b.IdleInterval;a.message=void 0;a.da=1;a.vb=void 0;a.B="#"+b.BubbleId;a.ca=b.onbubble;a.wa=b.onplay;a.Aa=b.onstop;a.va=b.onmute;a.Db=b.onaction;a.ya=b.onseek;a.za=b.onsetter;a.P=b.onfinish;a.W=b.behavior;a.G=!1;a.g=0;a.K=0;a.gb=function(b){a.fa=b.split("\\n");a.g=0};a.fb=function(b){a.Ba=b};a.getParams=function(){return a.Ba};a.getName=function(){return a.name};a.getAlias=function(){return a.ka};a.qa=function(){return a.g<
a.fa.length};a.Za=function(){if(a.qa())return a.g+=1,a.fa[a.g-1]};a.registerCustomAction=function(b,f){a.A[b]=f};a.update=function(b,f){a.kb();return void 0==a.A[b]||void 0==a.A[b].Ga||a.A[b].Ja!=f.Ja?!1:a.A[b].Ga(void 0,f)};a.kb=function(){a.da=1;void 0!=a.N&&clearTimeout(a.N)};a.v=function(b,f){void 0!=f&&(a.first=f.ja);a.K=0;a.message=b;void 0!=a.N&&clearTimeout(a.N);a.G&&(clearTimeout(a.timeout),a.G=!1);a.gb(b);a.Ea()};a.Ea=function(){retVal=!0;void 0!=a.wa&&k.F&&(retVal=!a.wa(a));retVal&&a.show()};
a.show=function(){a.Ma(a.Za())};a.skip=function(){clearTimeout(a.timeout);a.mute()};a.repeat=function(){a.v(a.message);a.da++};a.about=function(){temp=a.message;a.v("Hi, my name is "+a.ka+".");a.message=temp};a.getTextId=function(){return a.K};a.Ma=function(b){void 0!=a.ca?(px={},px.Text=b,px.Element=$(a.B),a.ca(px)):$(a.B).text(b);retVal=a.G=!0;void 0!=a.ya&&k.F&&(retVal=!a.ya(a));retVal&&(a.timeout=setTimeout(function(){a.G&&a.mute()},b.length*a.speed));$(a.B).fadeIn("fast",function(){a.first&&
(k.hb(a.Ba),a.first=!1);k.update(a)})};a.isSpeaking=function(){return a.G};a.mute=function(){void 0!=a.va&&a.va(a);$(a.B).fadeOut("slow",function(){a.qa()?(a.K+=1,a.Ea()):a.jb()})};a.jb=function(){void 0!=a.Aa&&a.Aa(a);a.K=0;void 0!=a.ra&&(a.N=setTimeout(function(){a.repeat()},a.ra*a.da))};return a}
function l(){return hR={update:function(b){$("#history").empty();$.each(b.ba,function(){historyItem=this;$("<strong>"+historyItem.ga+"</strong><p>"+historyItem.b+"</p>").appendTo("#history")});$hide=$("<a>hide</a>");$hide.click(function(){b.hide();$("#history_panel").fadeOut("fast");$("#history").empty()}).appendTo("#history")},bb:function(b){$("#history_panel").fadeIn("fast");hR.update(b)}}}
function m(){mH={ba:{},Fa:{},Fb:{},Ca:void 0,aa:!1};mH.h=l();mH.g=0;mH.Da=function(b){mH.Fa[b.q]=!0;mH.ba[mH.g]=b;mH.g++;mH.update()};mH.eb=function(b){mH.Ca=b};mH.wb=function(){return mH.Ca};mH.Xa=function(b){return!0==mH.Fa[b]};mH.show=function(){mH.aa=!0;mH.h.bb(mH)};mH.update=function(){mH.aa&&mH.h.update(mH)};mH.hide=function(){mH.aa=!1};return mH}
function n(){aU={f:[],k:[]};var b=m();aU.register=function(a,b){aU.f[a]=b;void 0!=b.W&&b.W(b)};aU.reset=function(){aU.k=[]};aU.ea=function(a){if(isNaN(a.w))return!1;void 0==aU.k[a.e]&&(aU.k[a.e]=0);if("+="==a.T)aU.k[a.e]+=Number(a.w);else if("="==a.T)aU.k[a.e]=Number(a.w);else return!1;void 0!=aU.H&&aU.H(a);return!0};aU.M=function(a){return aU.k[a]};aU.Va=function(){for(var a in aU.f)void 0!=aU.f[a].za&&aU.f[a].za()};aU.oa=function(a){return aU.f[a]};aU.t=function(){return b};aU.v=function(a,d){void 0!=
d.p&&void 0!=aU.f[d.p]&&($v=$(aU.f[d.p].B),void 0!=$v&&"hide"!=d.Ha&&(b.Da({ga:d.p,b:a}),aU.f[d.p].v(a,d)))};return aU}
function q(b,a){pR={};pR.i=a;pR.$=void 0;pR.D=b.initState;pR.O=b.isAutostart;pR.xml=void 0;pR.load=function(a){pR.$=!1;$.ajax({type:"GET",url:a,dataType:"xml",success:function(a){pR.xml=$(a);pR.$=!0;void 0!=pR.O&&void 0!=pR.D&&pR.O&&pR.i.J(pR.D)},error:function(){alert("Dialog file "+a+" not found.")}})};pR.Ra=function(a){var b={};$.each(pR.i.Ka,function(e,c){b[c.charAt(0).toUpperCase()+c.substring(1)]=a.getAttribute(c)});b.b=b.Text;b.o=b.Target;b.S=b.Invoke;b.ob=b.Overtime;b.rb=b.Timeout;b.U=b.Sound;
b.ia=b.Id;void 0!=pR.i.la&&$.each(pR.i.la,function(e,c){b[c.charAt(0).toUpperCase()+c.substring(1)]=a.getAttribute(c)});return void 0==b.b?void 0:b};pR.Sa=function(){var a=element,b={};b.m=a.getAttribute("prop");$.each(pR.i.La,function(e,c){b[c.charAt(0).toUpperCase()+c.substring(1)]=a.getAttribute(c)});b.l=b.Goto;b.b=b.Text;b.ha=b.Condition;b.pb=b.Prop;b.n=b.Setter;b.U=b.Sound;b.S=b.Invoke;void 0!=pR.i.ma&&$.each(pR.i.ma,function(e,c){b[c.charAt(0).toUpperCase()+c.substring(1)]=a.getAttribute(c)});
return void 0==b.b&&void 0==GotoId?void 0:b};pR.Ya=function(a,b,e){diff=100-b;0<diff&&(p=Math.floor(diff/e),$.each(a,function(){void 0==this.m&&(this.m=p)}))};pR.$a=function(b){tokens=b.split(";");for(i=0;i<tokens.length;i++)0==tokens[i].indexOf("_")&&0<tokens[i].indexOf("=")&&(variables=tokens[i].split("="),isNaN(variables[1])?alert(tokens[i]+": invalid number format"):variables[0].indexOf("+")==variables[0].length-1?a.d.ea({e:variables[0].substring(0,variables[0].length-1),T:"+=",w:variables[1]}):
a.d.ea({e:variables[0],T:"=",w:variables[1]}));a.d.Va()};pR.Qa=function(a){var b=Math.floor(100*Math.random()+1),e=void 0,c=0;$.each(a,function(){if(pR.Wa(this,b,c))return e=this,!1;c+=Number(this.m);return!0});return e};pR.Wa=function(a,b,e){return b>e&&b<=e+Number(a.m)};pR.pa=function(){return pR.xml};return pR}
function t(b){iN={data:"",index:0,lastIndex:0,ba:"",L:0,H:void 0};void 0!=b&&void 0!=b.onvariable&&(iN.H=b.onvariable);iN.log=function(){};iN.evaluate=function(a){iN.data=decodeURI(a.replace(/\^/g,"&"));iN.index=0;iN.L=0;return r=iN.s()};iN.s=function(){expected=iN.next();if("("==expected){iN.L++;tmp=iN.s();expected=iN.next();if(")"==expected)return iN.L--,expected=iN.next(),"|"==expected?tmp|=iN.s():")"==expected?iN.I():"&"==expected?tmp&=iN.s():iN.u()||iN.c(expected,"& or |"),tmp;iN.c(expected,
")")}else{if("_"==expected)return tmp=iN.Pa(),expected=iN.next(),"|"==expected?tmp|=iN.s():"&"==expected?tmp&=iN.s():")"==expected?(0>=iN.L&&iN.c(expected,"unexpected )"),iN.I()):iN.u()||iN.c(expected,"& or |"),tmp;iN.c(expected,"_ or (")}};iN.Pa=function(){variable=iN.M();val=0;void 0!=iN.H&&(val=iN.H("_"+variable),void 0==val&&(val=0));expected=iN.next();"="==expected?tmp=val==iN.X():">"==expected?tmp=val>iN.X():"<"==expected?tmp=val<iN.X():iN.c("bad operator","expected ><=");return tmp};iN.yb=
function(a){return"x"==a?1:0};iN.M=function(){for(str="";;){expected=iN.next();if("="==expected||">"==expected||"<"==expected)return iN.I(),""==str?iN.c("empty name of property"):iN.log("got variable "+str),str;if("\n"==expected||iN.u()){iN.c(expected);break}else str+=expected}};iN.X=function(){str="";expected=iN.next();for("-"==expected?str+=expected:iN.I();;)if(expected=iN.next(),"1"==expected||"2"==expected||"3"==expected||"4"==expected||"5"==expected||"6"==expected||"7"==expected||"8"==expected||
"9"==expected||"0"==expected)str+=expected;else{if("&"==expected||"|"==expected||"\n"==expected||")"==expected||","==expected||"+"==expected||iN.u())return iN.I(),""==str&&iN.c("empty constant"),str;iN.c(expected,"");break}};iN.c=function(a,b){throw'error: "'+a+'",'+b;};iN.u=function(){return iN.index+1>iN.data.length};iN.I=function(){iN.index=iN.lastIndex};iN.ib=function(){for(;!(iN.index++,iN.u()||"\r"!=iN.data.charAt(iN.index-1)&&" "!=iN.data.charAt(iN.index-1)););};iN.next=function(){return iN.u()?
null:(iN.lastIndex=iN.index,iN.ib(),iN.data.charAt(iN.index-1))};return iN}
function u(){return rd={Oa:function(b,a){a.Z&&void 0!=b.ha&&1!=a.evaluate(b.ha)||(cssClass="",a.t().Xa(b.q)&&(cssClass="class=visited"),void 0!=b&&(s=void 0,void 0!=a.xa&&(s=a.xa(b)),void 0==s&&(s=$("<li "+cssClass+"></li>").html('<a href="#'+b.o+'_area">'+b.b+"</a>")),s.click({b:b.b,l:b.l,q:b.q,R:b.R,n:b.n,Ia:b},function(b){a.t().eb(b.data.R);a.t().Da({ga:"you",b:b.data.b,q:b.data.q});void 0!=b.data.n&&a.a.$a(b.data.n);a.J(b.data.l);void 0!=a.ua&&a.ua(b.data.Ia)}),s.appendTo("#answers")))},cb:function(b){return b},
sa:function(){$('<ul id="answers"></ul>').appendTo("#dialog")}}}
var k=function(){var b={init:function(a){b.a=void 0;b.h=void 0;b.d=n();b.r=void 0;b.C=a.chapterUrl;b.ta=a.onload;b.ua=a.onanswer;b.xa=a.onrender;b.Q=a.onsound;b.P=a.onfinish;b.la=a.attrCase;b.ma=a.attrReact;b.Ka="id text target sound overtime timeout invoke".split(" ");b.La="text goto condition invoke sound setter".split(" ");b.a=q(a,b);b.h=u();b.F=!1;b.F=a.isSoundEnabled;b.Z=!0;b.Y=void 0;!1==a.isExprEnabled&&(b.Z=!1);b.na=a.disableBubbleRender;b.V=1},invokeInit:function(){if(void 0==b.ta||void 0==
b.a)return!1;b.h.sa();b.ta();b.Ta();void 0!=b.C&&(b.Z&&(b.Y=t({onvariable:b.d.M})),b.a.load(b.C))},reset:function(){b.d.reset();b.J(b.a.D);temp=avatar.message},j:function(){return b.d},xb:function(){return b.h()},createAvatar:function(a){void 0==a.BubbleId&&(a.BubbleId="npc_bubble_"+b.V);void 0==a.Name&&(a.Name="avatar_"+b.V);a=g(a);if(void 0!=a&&void 0!=b.j())return b.j().register(a.name,a),b.V++,a},t:function(){return b.j().t()},gotoChapter:function(a){void 0!=a.nodeId&&(b.d.reset(),void 0!=a.chapterUrl&&
a.chapterUrl!=b.C?(b.a.D=a.nodeId,b.C=a.chapterUrl,b.a.O=!0,b.a.load(b.C)):b.J(a.nodeId))},J:function(a){if(void 0==b.a||!0!=b.a.$)return!1;$("#answers").empty();var d;b.a.pa().find("case[id="+a+"]").each(function(){d=this});a=b.a.Ra(d);if(void 0==a)return!1;!1==b.ab(a)&&b.show(a)},show:function(a){b.Ua(a)},hb:function(a){var d=0,f=0,e=0,c=[];nodeId=a.ia;b.a.pa().find("react[rel="+nodeId+"]").each(function(){element=this;params=b.a.Sa();params.q=nodeId+""+params.l;params.R=nodeId;params.o=a.o;void 0!=
params.m?e+=Number(params.m):f+=1;c[d]=params;d++;0==e&&b.h.Oa(params,b)});$("#answer_widget").fadeIn("slow");if(0<e){b.a.Ya(c,e,f);var h=b.a.Qa(c);void 0!=h&&void 0!=h.l&&setTimeout(function(){void 0!=h.n&&b.a.Eb(h.n);b.J(h.l)},5E3)}0==d&&void 0!=b.P&&b.P(a)},update:function(){},invokeActions:function(a){avatar=k.j().oa(b.r);void 0!=avatar&&void 0!=a.S&&avatar.update(a.S,a)},Ua:function(a){a.o!=b.r&&void 0!=a.o&&(b.j().v("",{p:b.r,Ha:"hide",ja:!0}),b.r=a.o);if(void 0==b.na||!1==b.na)a.b=b.h.cb(a.b);
avatar=k.j().oa(b.r);avatar.fb(a);b.j().v(a.b,{p:b.r,ja:!0})},zb:function(){b.t().show()},Ta:function(){if(!b.F||void 0==b.Q)return!1;px={Type:"INIT"};b.Q(px)},ab:function(a){if(!b.F||void 0==b.Q||void 0==a.U)return!1;px={Type:"PLAY"};px.Id=a.ia;px.Sound=a.U;px.Param=a;b.Q(px)},getVariable:function(a){return b.d.M(a)},setVariable:function(a,d){b.d.ea({e:a,w:d})},evaluate:function(a){if(void 0==b.Y||void 0==a||3>=a.length)return null;try{return r=b.Y.evaluate(a)}catch(d){return null}}};return b}(""),
ypi={};ypi.df=k;
